// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PM.DataAccess;

#nullable disable

namespace PM.DataAccess.Migrations
{
    [DbContext(typeof(ParkingManagerDbContext))]
    [Migration("20260912134139_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PM.Core.Entities.ParkingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ParkingSpaceId")
                        .HasColumnType("int");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("TimeIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeOut")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParkingSpaceId");

                    b.ToTable("ParkingSession");
                });

            modelBuilder.Entity("PM.Core.Entities.ParkingSpace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SpaceNumber")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ParkingSpace");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SpaceNumber = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            SpaceNumber = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            SpaceNumber = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            SpaceNumber = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            SpaceNumber = 5,
                            Status = 0
                        });
                });

            modelBuilder.Entity("PM.Core.Entities.ParkingSession", b =>
                {
                    b.HasOne("PM.Core.Entities.ParkingSpace", "ParkingSpace")
                        .WithMany()
                        .HasForeignKey("ParkingSpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParkingSpace");
                });
#pragma warning restore 612, 618
        }
    }
}
